/** ObjectARX raw capability catalog (from OBJECTARX-CAPABILITIES.md).
 *  Source of truth for the raw menu + coverage audit. Do not invent Win-only as enabled.
 */

export type CatalogStatus = "✅" | "🟡" | "❓" | "❌";
export type RawGroup =
  | "Database"
  | "Editor/Input/Selection"
  | "Documents/Events/Reactors"
  | "Advanced"
  | "UI/View/Plot/Mac"
  | "Win-only";
export type RawHandler = "native" | "command" | "disabled";
/** How verification evidence is classified for the matrix. */
export type VerificationKind =
  | "real"            // C++ handler ends in a real ARX call for this capability
  | "interactive"     // requires AutoCAD GUI session (acedGet*/jig/…)
  | "blocked_partial" // Mac partial/missing symbols — always blocked with diagnostic
  | "disabled";       // Win-only / not a public Mac plugin API

export type RawCapability = {
  id: string;
  name: string;
  api: string;
  group: RawGroup;
  catalogStatus: CatalogStatus;
  macAvailable: boolean;
  enabled: boolean;
  interactive: boolean;
  handler: RawHandler;
  verificationKind: VerificationKind;
  reason: string;
  note: string;
};

export const RAW_GROUPS: RawGroup[] = [
  "Database",
  "Editor/Input/Selection",
  "Documents/Events/Reactors",
  "Advanced",
  "UI/View/Plot/Mac",
  "Win-only",
];

export const RAW_CAPABILITIES: RawCapability[] = [
  {
    id: 'db.entity_curves',
    name: 'Entity đường cong cơ bản: line, circle, arc, ellipse, spline, point',
    api: 'AcDbLine, AcDbCircle, AcDbArc, AcDbEllipse, AcDbSpline, AcDbPoint (dbents.h) + AcDbBlockTableRecord::appendAcD',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Ctor C1 tất cả class export trong libacdb.dylib; appendAcDbEntity verified (__ZN20AcDbBlockTableRecord16appendAcDbEntityE...).',
  },
  {
    id: 'db.polyline',
    name: 'Polyline: lightweight (bulge/width), 2D/3D polyline',
    api: 'AcDbPolyline (addVertexAt, setBulgeAt), AcDb2dPolyline, AcDb3dPolyline (dbents.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Ctor cả 3 class export trong libacdb (34/36/26 symbol). Đọc lại vertex+bulge để tính chiều dài chính xác.',
  },
  {
    id: 'db.mline',
    name: 'Multiline (đường song song nhiều nét)',
    api: 'AcDbMline + AcDbMlineStyle (dbmline.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbMline ctor export trong libacdb (18 symbol).',
  },
  {
    id: 'db.text_mtext',
    name: 'Text đơn dòng và MText',
    api: 'AcDbText, AcDbMText (dbents.h): setTextString, setPosition, setHeight',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Ctor export trong libacdb (AcDbText 31, AcDbMText 63 symbol).',
  },
  {
    id: 'db.block',
    name: 'Block definition + Block reference (insert)',
    api: 'AcDbBlockTable::add + AcDbBlockTableRecord; AcDbBlockReference: setBlockTableRecord/setPosition/setScaleFactor',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbBlockReference ctor + AcDbSymbolTable::add đều export trong libacdb.',
  },
  {
    id: 'db.attribute',
    name: 'Attribute: định nghĩa và điền thuộc tính block',
    api: 'AcDbAttributeDefinition, AcDbAttribute::setAttributeFromBlock, AcDbBlockReference::appendAttribute (dbents.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified: setAttributeFromBlock + appendAttribute export trong libacdb.',
  },
  {
    id: 'db.dimension',
    name: 'Dimension đầy đủ 7 loại: rotated, aligned, radial, diametric, angular, ordinate, arc',
    api: 'AcDbRotatedDimension, AcDbAlignedDimension, AcDbRadialDimension, AcDbDiametricDimension, AcDb2LineAngularDimen',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Ctor tất cả 7 loại export trong libacdb.',
  },
  {
    id: 'db.hatch',
    name: 'Hatch: tô vùng theo pattern, boundary loop từ điểm hoặc entity',
    api: 'AcDbHatch (dbhatch.h): appendLoop (3 overload), setPattern',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified cả 3 overload appendLoop; AcDbHatch ~566 symbol trong libacdb — dùng thay MPolygon trên Mac.',
  },
  {
    id: 'db.leader',
    name: 'Leader và MLeader (chú thích mũi tên)',
    api: 'AcDbLeader (dblead.h), AcDbMLeader (dbmleader.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Ctor export trong libacdb (AcDbLeader 44, AcDbMLeader 78 symbol).',
  },
  {
    id: 'db.table',
    name: 'Table entity + TableStyle + DataLink (bảng thông minh trong bản vẽ)',
    api: 'AcDbTable (dbtable.h): setNumRows/Columns, setTextString, setColumnWidth; AcDbTableStyle; AcDbDataLink',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbTable export rất đầy đủ (hàng trăm symbol trong libacdb), AcDbDataLink 88 symbol — API bảng hoàn chỉnh trên Mac.',
  },
  {
    id: 'db.solid3d',
    name: '3D solid / Region (khối đặc ACIS)',
    api: 'AcDb3dSolid (dbsol3d.h), AcDbRegion (dbregion.h)',
    group: 'Database',
    catalogStatus: '🟡',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'blocked_partial',
    reason: 'AcDb3dSolid ctor not exported in libacdb on Mac (🟡)',
    note: 'Header đủ; libacdb chỉ export acrxGetClassDesc (class registered) nhưng KHÔNG có ctor trong libacdb/libaccore — implementation nằm',
  },
  {
    id: 'db.symbol_tables',
    name: 'Symbol tables đủ 9 loại: block, layer, linetype, textstyle, dimstyle, regapp, UCS, view, viewport',
    api: 'AcDbDatabase::getSymbolTable/getBlockTable/getLayerTable (dbmain.h), AcDbSymbolTable::add + newIterator, AcDb*',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'getSymbolTable export cho cả 9 loại; add + newIterator + BlockTableRecordIterator verified.',
  },
  {
    id: 'db.layer',
    name: 'Layer control: màu, linetype, freeze/lock, tạo layer mới',
    api: 'AcDbLayerTableRecord (dbsymtb.h): setColor, setLinetypeObjectId, setIsFrozen, setIsLocked',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Ctor + 162 symbol export trong libacdb.',
  },
  {
    id: 'db.entity_props',
    name: 'Thuộc tính chung entity: layer, màu, linetype, transform',
    api: 'AcDbEntity::setLayer/setColor/setLinetype/transformBy (dbmain.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified: setLayer (cả overload tên và ObjectId), setColor, setLinetype, transformBy(AcGeMatrix3d).',
  },
  {
    id: 'db.object_lifecycle',
    name: 'Vòng đời object: mở/đóng/xóa/nâng quyền',
    api: 'acdbOpenObject (dbmain.h/dbobjptr), AcDbObject::close/erase/upgradeOpen/downgradeOpen',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified đầy đủ, kể cả acdbOpenObjectOnLockedLayerForWrite. Nền tảng mọi thao tác đọc/sửa/xóa entity.',
  },
  {
    id: 'db.xdata',
    name: 'Xdata + RegApp: gắn dữ liệu mở rộng dạng resbuf vào entity',
    api: 'AcDbObject::xData/setXData (dbmain.h), resbuf + acutBuildList/acutNewRb/acutRelRb, acdbRegApp, AcDbRegAppTable',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified: xData/setXData, acutBuildList/NewRb/RelRb trong libacdb, acdbRegApp trong libaccore. Sample: database/xdata_dg. Cách nhẹ',
  },
  {
    id: 'db.xrecord',
    name: 'Extension dictionary + Xrecord: dữ liệu có cấu trúc lớn hơn xdata',
    api: 'AcDbObject::createExtensionDictionary/extensionDictionary (dbmain.h), AcDbXrecord::setFromRbChain/rbChain (dbx',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified; AcDbXrecord 73 symbol trong libacdb. Samples: database/xrecord_dg, xtsndict_dg.',
  },
  {
    id: 'db.nod',
    name: 'Named Object Dictionary và dictionary tùy biến',
    api: 'AcDbDatabase::getNamedObjectsDictionary (dbmain.h), AcDbDictionary::setAt/getAt (dbdict.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified — nơi neo dictionary \'MEP_STUDIO\' chứa registry app-level trong DWG.',
  },
  {
    id: 'db.handle',
    name: 'Handle / ObjectId: định danh ổn định của object',
    api: 'AcDbObject::getAcDbHandle, AcDbDatabase::getAcDbObjectId(handle), acdbGetObjectId/acdbGetAdsName/acdbHandEnt (',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified đầy đủ — cơ chế đồng bộ 2 chiều cốt lõi: app lưu handle hex, plugin resolve về ObjectId.',
  },
  {
    id: 'db.transaction',
    name: 'Transaction: gom nhiều thao tác thành một đơn vị undo',
    api: 'acdbTransactionManager (dbtrans.h): startTransaction/endTransaction/abortTransaction/getObject',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbImpTransactionManager::start/endTransaction export trong libacdb — chạy được.',
  },
  {
    id: 'db.side_database',
    name: 'Side-database: mở/tạo/lưu DWG ngoài document',
    api: 'AcDbDatabase(buildDefaultDrawing, noDocument), readDwgFile, saveAs (dbmain.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified: ctor Ebb, readDwgFile (2 overload, có OpenMode+password), saveAs (DwgVersion+SecurityParams). Dùng cho thư viện block ng',
  },
  {
    id: 'db.wblock_insert',
    name: 'Wblock (xuất) và Insert (nhập) database',
    api: 'AcDbDatabase::wblock (3 dạng), AcDbDatabase::insert (matrix hoặc tên block) (dbmain.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified: 4 overload wblock + 3 overload insert trong libacdb.',
  },
  {
    id: 'db.deep_clone',
    name: 'Deep clone / wblock clone giữa database + id mapping',
    api: 'AcDbDatabase::deepCloneObjects, wblockCloneObjects (dbmain.h), AcDbIdMapping + AcDbIdPair (dbidmap.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified (có DuplicateRecordCloning); AcDbIdMapping::assign/compute. Samples: database/deepclone_dg, clonenod_dg (clone dict trong',
  },
  {
    id: 'db.purge',
    name: 'Purge và đếm tham chiếu',
    api: 'AcDbDatabase::purge(ObjectIdArray/ObjectIdGraph), countHardReferences (dbmain.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified cả 2 overload purge + countHardReferences.',
  },
  {
    id: 'db.audit',
    name: 'Audit / kiểm tra tính toàn vẹn',
    api: 'AcDbObject::audit(AcDbAuditInfo*), AcDbDatabase::auditXData, auditCheck* helpers (dbaudita.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'blocked_partial',
    reason: 'AcDbAuditInfo/auditXData crashes AutoCAD Mac session',
    note: 'Verified. Không có AcDbDatabase::audit() public — audit toàn DB qua lệnh AUDIT hoặc audit từng object.',
  },
  {
    id: 'db.units',
    name: 'Đơn vị và header variables của database',
    api: 'AcDbDatabase::insunits/setInsunits, measurement, lunits, clayer/setClayer, cecolor, textstyle, dimstyle (dbmai',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified — guard đơn vị (mm vs inch) trước khi bóc khối lượng.',
  },
  {
    id: 'db.extents',
    name: 'Extents: bounding box của entity và bản vẽ',
    api: 'AcDbEntity::getGeomExtents(AcDbExtents&), AcDbExtents::set/addPoint/addExt/addBlockExt/transformBy, AcDbDataba',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified đầy đủ.',
  },
  {
    id: 'db.wcs_ucs',
    name: 'Chuyển đổi tọa độ WCS/UCS và viewport hiện hành',
    api: 'acdbWcs2Ucs, acdbUcs2Wcs, acdbGetCurVportId (dbxutil.h)',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified trong libacdb.',
  },
  {
    id: 'db.xref',
    name: 'Xref: attach, detach, bind, reload, resolve + phân tích đồ hình',
    api: 'acdbAttachXref, acdbDetachXref, acdbBindXrefs, acdbXBindXrefs, acdbReloadXrefs, acdbResolveCurrentXRefs (acdbx',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified cả 6 hàm + acdbAttachXrefWithConcatenatedName; AcDbXrefGraph 50 symbol; có cả xref compare reactor.',
  },
  {
    id: 'db.ads_ent',
    name: 'Truy cập entity kiểu ads/DXF-list (entget/entmake AutoLISP-style)',
    api: 'acdbEntGet/acdbEntGetX, acdbEntMod, acdbEntMake/acdbEntMakeX, acdbEntNext/acdbEntLast, acdbTblSearch',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified trong libaccore.dylib — cần AutoCAD chạy, không dùng cho side-database thuần. Cầu serialize resbuf DXF-group → JSON.',
  },
  {
    id: 'db.group',
    name: 'Group: nhóm entity có tên',
    api: 'AcDbGroup (dbgroup.h): append(ObjectId), iterator, trong Group Dictionary',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbGroup 99 symbol trong libacdb. Sample: database/groups_dg. Mỗi pipe run = 1 group.',
  },
  {
    id: 'db.layout',
    name: 'Layout, paper space viewport, layout manager',
    api: 'AcDbLayout (dblayout.h), AcDbViewport (dbents.h): setCenterPoint/setViewCenter/setCustomScale; AcDbLayoutManag',
    group: 'Database',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbLayout ctor (152 symbol), AcDbViewport ctor (118 symbol), AcDbLayoutManager 70 symbol.',
  },
  {
    id: 'db.wipeout',
    name: 'Wipeout (che nền)',
    api: 'AcDbWipeout (dbwipeout/imgent)',
    group: 'Database',
    catalogStatus: '🟡',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'blocked_partial',
    reason: 'AcDbWipeout in separate module — not in libacdb (🟡)',
    note: 'Không thấy symbol trong libacdb/libaccore — nằm trong module AcWipeoutObj nạp runtime; cần test khi AutoCAD chạy.',
  },
  {
    id: 'db.mpolygon',
    name: 'MPolygon',
    api: 'AcDbMPolygon (acmpolygonobj)',
    group: 'Database',
    catalogStatus: '❓',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Chưa xác nhận / không phải API plugin công khai trên Mac',
    note: '0 symbol trong cả 4 dylib chính; trên Windows là .dbx riêng — có thể không ship trên Mac. Dùng AcDbHatch thay thế.',
  },
  {
    id: 'ed.get_point',
    name: 'Nhập điểm tương tác trên canvas',
    api: 'acedGetPoint, acedGetCorner (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'libaccore: __Z12acedGetPointPKdPKwPd (C++ mangled, không extern-C).',
  },
  {
    id: 'ed.get_string',
    name: 'Nhập string/keyword tại command line',
    api: 'acedGetString, acedGetKword (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'libaccore: bản AcString + overload bool.',
  },
  {
    id: 'ed.get_number',
    name: 'Nhập số (real/int/dist/angle)',
    api: 'acedGetReal, acedGetInt, acedGetDist, acedGetAngle (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Verified đủ 4 hàm trong libaccore.',
  },
  {
    id: 'ed.ssget',
    name: 'Selection set query (ssget) có filter',
    api: 'acedSSGet, acedSSLength, acedSSName, acedSSNameX, acedSSFree, acedSSAdd (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Verified đầy đủ trong libaccore; hỗ trợ filter resbuf (layer, entity type).',
  },
  {
    id: 'ed.ssget_first',
    name: 'Pickfirst selection get/set',
    api: 'acedSSGetFirst, acedSSSetFirst (aced.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Verified — đọc thứ user đang chọn và set selection từ code.',
  },
  {
    id: 'ed.entsel',
    name: 'Pick 1 entity (kể cả nested trong block)',
    api: 'acedEntSel, acedNEntSel (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Verified; acedNEntSel pick được nested entity trong block.',
  },
  {
    id: 'ed.highlight_subent',
    name: 'Highlight subentity + selection filter',
    api: 'acedSSGet/acedSSNameX + AcDbFullSubentPath + AcDbEntity::highlight; AcEdSSGetFilter',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'acedSSGet=6, AcEdSSGetFilter=14 symbol libaccore. Sample: entity/hilight_dg (GS marker).',
  },
  {
    id: 'ed.command_s',
    name: 'Chạy lệnh programmatic (synchronous, non-fiber)',
    api: 'acedCommandS, acedCmdS (acedCmdNF.h); acedCommand cũ',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: '_acedCommandS/_acedCmdS extern-C thật trong libaccore. Phải gọi trong command context.',
  },
  {
    id: 'ed.reg_cmds',
    name: 'Đăng ký native custom commands',
    api: 'acedRegCmds->addCommand (accmd.h, AcEdCommandStack)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcEdImpCommandStack::addCommand verified; macro acedRegCmds trong accmd.h. Nền cho bộ lệnh MEPPIPE/MEPBOM/MEPQA.',
  },
  {
    id: 'ed.printf',
    name: 'In ra command line',
    api: 'acutPrintf (acutads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Symbol nằm trong libacdb.dylib (không phải libaccore).',
  },
  {
    id: 'ed.post_prompt',
    name: 'Refresh command prompt sau output bất đồng bộ',
    api: 'acedPostCommandPrompt (aced.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified trong libaccore.',
  },
  {
    id: 'ed.sysvar',
    name: 'Đọc/ghi system variable',
    api: 'acedGetVar, acedSetVar (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified — đọc DWGNAME/DWGPREFIX/CLAYER kèm event; set OSMODE/CLAYER trước khi vẽ tự động.',
  },
  {
    id: 'ed.object_pointer',
    name: 'RAII smart pointer mở/đóng DB object',
    api: 'AcDbObjectPointer<T> (dbobjptr.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '🟡',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: 'header-only RAII; uses acdbOpenObject',
    note: 'Template header-only; hàm nền acdbOpenObject đã verified — dùng an toàn trên Mac.',
  },
  {
    id: 'ed.grdraw',
    name: 'Temporary graphics (vẽ đồ họa tạm trên canvas)',
    api: 'acedGrDraw, acedGrVecs, acedGrText, acedGrRead (acedads.h)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Đủ bộ symbol trong libaccore — preview tuyến ống, chớp-highlight đối tượng lỗi QA.',
  },
  {
    id: 'ed.input_point',
    name: 'Input point monitor/filter — tooltip và can thiệp điểm nhập',
    api: 'AcEdInputPointMonitor, AcEdInputPointFilter, AcEdInputContextReactor, AcEdInputPointManager (qua AcApDocument)',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Monitor=50, Filter=34, Manager=6 symbol libaccore. Sample: reactors/inputpoint — Monitor appendToTooltipText, Filter được SỬA điểm',
  },
  {
    id: 'ed.custom_osnap',
    name: 'Custom OSNAP mode riêng',
    api: 'AcDbCustomOsnapMode + acdbCustomOsnapManager()->addCustomOsnapMode',
    group: 'Editor/Input/Selection',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: '8 symbol libacdb + 29 tham chiếu libaccore (glyph/tooltip pipeline). Không có sample riêng.',
  },
  {
    id: 'doc.manager',
    name: 'Document manager: mở/đóng/kích hoạt/tạo document',
    api: 'acDocManager (acdocman.h): appContextOpenDocument, closeDocument, activateDocument, newDocument',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'acDocManagerPtr + AcApDocImpManager::open/close/activate/newDocument đều có symbol.',
  },
  {
    id: 'doc.send_string',
    name: 'Gửi chuỗi lệnh vào document',
    api: 'AcApDocManager::sendStringToExecute (acdocman.h)',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Chính là API MepBridge đang dùng — xác nhận hoạt động thực tế. Giữ làm escape hatch tổng quát.',
  },
  {
    id: 'doc.lock',
    name: 'Document locking để ghi DB an toàn',
    api: 'acDocManager->lockDocument / unlockDocument, lockCurDocument (acdocman.h)',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified. Bắt buộc khi daemon/FSEvents trigger ghi database ngoài command context — tránh crash.',
  },
  {
    id: 'doc.execute_context',
    name: 'Thực thi callback trong command/application context',
    api: 'AcApDocManager::beginExecuteInCommandContext / beginExecuteInApplicationContext (acdocman.h)',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Export trực tiếp trên class public — cách chuẩn để job từ file-watch chạy code native, nền tảng nâng cấp lớn nhất cho MepBridge.',
  },
  {
    id: 'doc.doc_events',
    name: 'Realtime document events (open/close/switch/lock)',
    api: 'AcApDocManagerReactor (acdocman.h): documentCreated, documentToBeDestroyed, documentActivated, documentBecameC',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: '__ZTV21AcApDocManagerReactor + addReactor verified (24 symbol); virtuals xác nhận trong header.',
  },
  {
    id: 'doc.list_docs',
    name: 'Liệt kê documents đang mở',
    api: 'AcApDocManager::newAcApDocumentIterator, documentCount (acdocman.h)',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Verified — nâng cấp tính năng đếm documents hiện có của MepBridge.',
  },
  {
    id: 'doc.doc_window',
    name: 'Quản lý document window (tab bản vẽ) + reactor',
    api: 'AcApDocWindow / AcApDwgDocWindow / AcApDocWindowReactor (AcApDocWindow.h)',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'addReactor/close/setDocument có symbol trong libaccore; không guard Windows.',
  },
  {
    id: 'doc.cmd_events',
    name: 'Realtime command lifecycle events',
    api: 'AcEditorReactor via acedEditor->addReactor (aced.h): commandWillStart, commandEnded, commandCancelled, command',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: '__ZTV15AcEditorReactor (52 symbol libaccore) + AcEditorReactorEx; acedEditor qua acrxSysRegistry (libacfirst.dylib).',
  },
  {
    id: 'doc.rx_events',
    name: 'Drawing/database lifecycle events (open, save)',
    api: 'AcRxEventReactor via acrxEvent->addReactor (rxevent.h): dwgFileOpened, databaseConstructed, databaseToBeDestro',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: '__ZTV16AcRxEventReactor + desc/rxInit trong libacdb; virtuals xác nhận rxevent.h.',
  },
  {
    id: 'doc.db_reactor',
    name: 'Per-database entity change events',
    api: 'AcDbDatabaseReactor (dbmain.h): objectAppended, objectModified, objectErased, headerSysVarChanged',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbImpDatabase::addReactor/remove verified (22 symbol). Callback chạy rất thường xuyên — chỉ ghi nhận ObjectId, xử lý sau ở comma',
  },
  {
    id: 'doc.object_reactor',
    name: 'Per-object change events',
    api: 'AcDbObjectReactor (dbmain.h): modified, erased, goodbye, openedForModify',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'desc/rxInit/C1/D1 + AcDbImpObject::addReactor verified (31 symbol).',
  },
  {
    id: 'doc.persistent_reactor',
    name: 'Persistent reactor — ràng buộc giữa các đối tượng, lưu bền trong DWG',
    api: 'AcDbObject::addPersistentReactor + custom AcDbObject reactor class',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'addPersistentReactor 4 symbol libacdb. Sample: reactors/persreac_dg — ràng buộc sống qua save/open.',
  },
  {
    id: 'doc.protocol_reactor',
    name: 'Protocol reactor — custom block insertion/alignment points',
    api: 'AcRxProtocolReactor + AcDbBlockInsertionPoints',
    group: 'Documents/Events/Reactors',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: '7 symbol libacdb. Sample: reactors/ProtocolReactors_dg — block nhiều insertion point + tự xoay theo geometry khi insert.',
  },
  {
    id: 'adv.bundle',
    name: 'Đóng gói & nạp plugin trên Mac (bundle + entrypoint)',
    api: 'acrxEntryPoint, acedRegCmds->addCommand, acrxRegisterAppMDIAware; ARX=.bundle, DBX=.framework, 64-bit, Xcode +',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'guide.txt SDK mô tả đầy đủ; MepBridge đang chạy nên đã kiểm chứng thực tế.',
  },
  {
    id: 'adv.jig',
    name: 'Jig / dynamic preview khi vẽ (kéo chuột entity cập nhật realtime)',
    api: 'AcEdJig (dbjig.h): sampler()/update()/entity()/drag(); acedDragGen',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: '271 symbol AcEdJig trong libaccore; acedDragGen có. Sample: database/elipsjig_dg (đã đọc source) — acquirePoint + keyword trong sa',
  },
  {
    id: 'adv.overrule',
    name: 'Overrule framework — \'độ\' entity chuẩn thành đối tượng MEP không cần custom entity',
    api: 'AcDbObjectOverrule, AcGiDrawableOverrule, AcDbGripOverrule, AcDbOsnapOverrule, AcDbTransformOverrule, AcDbProp',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Toàn bộ họ overrule trong libacdb (588 dòng chứa \'Overrule\'). Pattern adndevblog/keanw khuyên dùng — file mở máy khác vẫn là LINE',
  },
  {
    id: 'adv.custom_entity',
    name: 'Custom entity / custom object (class riêng lưu trong DWG)',
    api: 'AcDbEntity/AcDbObject subclass + ACRX_DXF_DEFINE_MEMBERS + dwgIn/OutFields + dxfIn/OutFields + worldDraw',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Sample: editor/custobj_dg. AcGiWorldDraw 237 symbol libacdb. LƯU Ý: máy khác cần object enabler nếu không entity thành proxy — ưu',
  },
  {
    id: 'adv.protocol_ext',
    name: 'Protocol extension — gắn hành vi mới cho class có sẵn lúc runtime',
    api: 'AcRxObject::queryX/x + ACRX_DECLARE_MEMBERS, AcRxClass::addX',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcRxClass 357 symbol libacdb (addX/queryX inline nhưng RTTI runtime đầy đủ). Samples: entity/tempapp_dg (protocol ENERGY), misc/fa',
  },
  {
    id: 'adv.fields',
    name: 'Fields + custom field evaluator — nhãn/khung tên tự tính',
    api: 'AcDbField, AcFdFieldEngine, AcFdFieldEvaluator, acdbEvaluateFields',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbField=262, AcFdFieldEvaluator=62, AcFdFieldEngine=22, acdbEvaluateFields=4 symbol libacdb — cả cơ chế đăng ký evaluator custom',
  },
  {
    id: 'adv.long_transaction',
    name: 'Long transaction (cơ chế REFEDIT) — sửa block in-place',
    api: 'AcDbLongTransaction + acApLongTransactionManager (checkOut/checkIn)',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'AcDbLongTransaction=32 symbol libacdb, manager=7 symbol libaccore. Sample: database/longtrans_dg.',
  },
  {
    id: 'adv.constraints',
    name: 'Parametric constraints + dynamic block',
    api: 'AcDbAssoc2dConstraintGroup, AcDbAssocNetwork; AcDbDynBlockReference',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: '115/44/90 symbol libacdb. API phức tạp — xếp giai đoạn sau.',
  },
  {
    id: 'adv.acgi',
    name: 'AcGi graphics primitives — mesh/shell/polygon/text trong worldDraw',
    api: 'AcGiWorldDraw/AcGiViewportDraw + geometry().mesh()/shell()/polygon(), subEntityTraits',
    group: 'Advanced',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'AcGiWorldDraw 237 symbol libacdb + 122 libaccore. Samples graphics/: mesh_dg, shell_dg, traits_dg, viewgeom_dg, teselate_dg, coord',
  },
  {
    id: 'ui.view_zoom',
    name: 'Điều khiển view/zoom từ C++',
    api: 'acgsGetCurrentAcGsView(int), acgsSetViewParameters(int, AcGsView*, bool,bool,bool), acedSetCurrentView (acgs.h',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Cả 3 symbol trong libaccore. Lấy AcGsView* rồi gọi virtual zoom/setView qua vtable.',
  },
  {
    id: 'ui.zoom_internal',
    name: 'Zoom nội bộ (không có trong header public)',
    api: 'acedZoomAuto(short) / acedZoomAuto(short,double,double,double,double)',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'blocked_partial',
    reason: 'acedZoomAuto internal — no public header',
    note: 'Symbol có trong libaccore nhưng KHÔNG khai báo trong header SDK — API nội bộ, không nên dựa vào; dùng acgsSetViewParameters hoặc l',
  },
  {
    id: 'ui.plot',
    name: 'Plot/Publish API — in PDF programmatically',
    api: 'AcPlPlotFactory::createPublishEngine/createPreviewEngine, AcPlPlotEngine::beginPlot/beginDocument/beginPage, A',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Không có libAcPl.dylib riêng — toàn bộ AcPl* trong libaccore (39 symbol AcPlPlotEngine) + libpltcfgmgr/libplotgrad hỗ trợ; header',
  },
  {
    id: 'ui.statusbar',
    name: 'Status bar & tray item của AutoCAD',
    api: 'acedGetApplicationStatusBar() → AcApStatusBar*, AcPane, AcTrayItem (AcStatusBar.h)',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Symbol verified libaccore; interface ảo gọi qua vtable. Implementation Mac là Objective-C (AcStatusBar.framework).',
  },
  {
    id: 'ui.cocoa',
    name: 'Plugin mở cửa sổ Cocoa riêng trong AutoCAD (Objective-C++)',
    api: 'Template ArxWithCocoa.xctemplate + EnableCocoaThreading() (libCocoaAPI.dylib)',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Template chính chủ Autodesk tại /Library/Developer/Autodesk/ObjectARX 2027/utils/templates/; plugin in-process tạo được NSWindow/N',
  },
  {
    id: 'ui.viewcube',
    name: 'ViewCube / SteeringWheel control',
    api: 'acedCreateSteeringWheel(), acedDestroyViewCube(AcEdViewCube*) (AcEdViewCube.h, AcEdSteeringWheel.h)',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Symbol trong libaccore; header không guard Windows.',
  },
  {
    id: 'ui.inplace_text',
    name: 'In-place text editor (sửa text/mtext tại chỗ)',
    api: 'AcEdInplaceTextEditor (AcEdInplaceTextEditor.h)',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: true,
    handler: 'command',
    verificationKind: 'interactive',
    reason: 'Cần session AutoCAD GUI / command context',
    note: 'Symbol insertFile... trong libaccore; header không guard Windows.',
  },
  {
    id: 'ui.main_wnd',
    name: 'Main window handle (HWND giả lập trên Mac)',
    api: 'adsw_acadMainWnd() → HWND (acedads.h:59)',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '✅',
    macAvailable: true,
    enabled: true,
    interactive: false,
    handler: 'native',
    verificationKind: 'real',
    reason: '',
    note: 'Symbol có nhưng HWND là kiểu giả lập từ WinStubs.h/libWinAPI.dylib — KHÔNG phải NSWindow thật; muốn parent cửa sổ Cocoa dùng [NSAp',
  },
  {
    id: 'ui.internal_ui',
    name: 'UI stack nội bộ AutoCAD Mac (chỉ tham khảo kiến trúc)',
    api: 'Qt 6 (QtWidgets/QtGui), AcOCUi.framework, AcOCUiControls.framework, AcToolbar/AcStatusBar/CoreDialogs (Objecti',
    group: 'UI/View/Plot/Mac',
    catalogStatus: '❓',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Chưa xác nhận / không phải API plugin công khai trên Mac',
    note: 'Frameworks tồn tại trong app bundle nhưng SDK KHÔNG có header public — UI nội bộ, không phải API plugin được hỗ trợ. Không xây tín',
  },
  {
    id: 'win.mfc',
    name: 'MFC dialog framework AcUi/AdUi (CAcUiDialog, CAdUiDialog, CWnd)',
    api: 'acui.h / acuiDialog.h / adui.h + ~50 header AcUi*/AdUi*',
    group: 'Win-only',
    catalogStatus: '❌',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Win-only / KHÔNG có trên Mac',
    note: 'Mac SDK ship afxwin.h là STUB (#error nếu không _ADESK_MAC_) — không có MFC runtime, không symbol CAcUiDialog/InitAcUiDLL trong dy',
  },
  {
    id: 'win.tool_palette',
    name: 'Tool Palette / PaletteSet',
    api: 'aduiPaletteSet.h / aduiPalette.h (CAdUiPaletteSet)',
    group: 'Win-only',
    catalogStatus: '❌',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Win-only / KHÔNG có trên Mac',
    note: 'Class bọc trong #ifndef _ADESK_MAC_ (dòng 59) — loại trừ tường minh trên Mac. Thay bằng NSPanel Cocoa.',
  },
  {
    id: 'win.opm',
    name: 'OPM Property Palette (properties tùy biến trên palette Properties)',
    api: 'dynprops.h (IPropertyManager, IDynamicProperty), opmdialog.h, category.h',
    group: 'Win-only',
    catalogStatus: '❌',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Win-only / KHÔNG có trên Mac',
    note: 'dynprops.h/category.h bọc #ifdef _ADESK_WINDOWS_; opmdialog.h thuần COM. Hiển thị property MEP trong panel riêng của app thay thế.',
  },
  {
    id: 'win.com_ole',
    name: 'COM/OLE automation & ActiveX wrapper',
    api: 'oleaprot.h (AcAxOleLinkManager), axobjref.h, dcdispid.h',
    group: 'Win-only',
    catalogStatus: '❌',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Win-only / KHÔNG có trên Mac',
    note: 'oleaprot.h bọc trọn #ifdef _ADESK_WINDOWS_. Không có COM trên Mac — điều khiển từ ngoài process phải qua file bridge + sendStringT',
  },
  {
    id: 'win.dotnet',
    name: '.NET managed API (AcMgd/C++-CLI interop)',
    api: 'mgdhost.h / mgdinterop.h / mgdhost-core2d.h; acdbmgd/acmgd',
    group: 'Win-only',
    catalogStatus: '❌',
    macAvailable: false,
    enabled: false,
    interactive: false,
    handler: 'disabled',
    verificationKind: 'disabled',
    reason: 'Win-only / KHÔNG có trên Mac',
    note: 'mgdinterop.h include vcclr.h/gcroot.h (C++/CLI) — chỉ MSVC/Windows. Forum Autodesk xác nhận C# plugin không chạy AutoCAD Mac; plug',
  },
];

export function macAvailableCapabilities(): RawCapability[] {
  return RAW_CAPABILITIES.filter((c) => c.macAvailable);
}

export function enabledRawCapabilities(): RawCapability[] {
  return RAW_CAPABILITIES.filter((c) => c.enabled);
}

export function byCapabilityId(id: string): RawCapability | undefined {
  return RAW_CAPABILITIES.find((c) => c.id === id);
}

export function capabilitiesByGroup(): Record<RawGroup, RawCapability[]> {
  const out = {} as Record<RawGroup, RawCapability[]>;
  for (const g of RAW_GROUPS) out[g] = [];
  for (const c of RAW_CAPABILITIES) out[c.group].push(c);
  return out;
}

export function coverageSummary() {
  const mac = macAvailableCapabilities();
  const win = RAW_CAPABILITIES.filter((c) => c.group === "Win-only" || c.catalogStatus === "❌");
  const enabledWin = win.filter((c) => c.enabled);
  return {
    total: RAW_CAPABILITIES.length,
    macAvailable: mac.length,
    enabled: enabledRawCapabilities().length,
    interactive: RAW_CAPABILITIES.filter((c) => c.interactive).length,
    winOnly: win.length,
    enabledWinOnly: enabledWin.length,
    real: RAW_CAPABILITIES.filter((c) => c.verificationKind === "real").length,
    blockedPartial: RAW_CAPABILITIES.filter((c) => c.verificationKind === "blocked_partial").length,
    ids: mac.map((c) => c.id),
  };
}

/** Map catalog row → matrix verification status (honest, not auto-pass). */
export function verificationFor(c: RawCapability): {
  status: "pass" | "fail" | "blocked";
  reason: string;
} {
  switch (c.verificationKind) {
    case "disabled":
      return { status: "blocked", reason: c.reason || "disabled / not on Mac" };
    case "blocked_partial":
      return {
        status: "blocked",
        reason: c.reason || "partial Mac surface — handler returns blocked",
      };
    case "interactive":
      return {
        status: "blocked",
        reason: "interactive — requires AutoCAD GUI session (MEPRAW)",
      };
    case "real":
      return {
        status: "pass",
        reason: "native handler ends in real ObjectARX call (shipped C++)",
      };
    default:
      return { status: "fail", reason: "unknown verificationKind" };
  }
}
